server:
  port: 8081
  error:
    include-stacktrace: on_param
    include-exception: false
    include-message: on_param


spring:
  application:
    name: bank-app-backend

  datasource:
    url: ${AVITO_BACKEND_DB_URL:jdbc:postgresql://localhost:5432/avito-backend}
    username: ${AVITO_BACKEND_DB_USER:postgres}
    password: ${AVITO_BACKEND_DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  jackson:
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: DEBUG

app:
  security:
    jwt:
      expiration: 86400000 # 1 day
      secretKey: 0917b13a9091915d54b6336f45909539cce452b3661b21f386418a257883b30a

springdoc:
  swagger-ui:
    path: /docs
